services:
  - type: web
    name: talleres-backend
    env: python
    region: ohio
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER_DB_URL
        fromDatabase:
          name: talleres-db
          property: connectionString
      # Estas variables deberán ser configuradas en el panel de Render
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: BASE_URL
        sync: false
      - key: PROJECT_NAME
        value: "Talleres API"

databases:
  - name: talleres-db
    region: ohio
    plan: free
    databaseName: talleres
    user: talleres_user
