"""Add bitacora_acceso

Revision ID: 2474690a3266
Revises: c885843b8964
Create Date: 2026-05-29 10:55:33.062303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2474690a3266'
down_revision: Union[str, Sequence[str], None] = 'c885843b8964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('email_intentado', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('accion', sa.Enum('LOGIN_EXITOSO', 'LOGIN_FALLIDO', 'LOGOUT', name='accionacceso'), nullable=False),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.Column('fecha_hora', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_acceso_id'), 'bitacora_acceso', ['id'], unique=False)
    op.create_index(op.f('ix_bitacora_acceso_id_usuario'), 'bitacora_acceso', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bitacora_acceso_id_usuario'), table_name='bitacora_acceso')
    op.drop_index(op.f('ix_bitacora_acceso_id'), table_name='bitacora_acceso')
    op.drop_table('bitacora_acceso')
    # ### end Alembic commands ###
