"""add cotizada to EstadoSolicitudServicio

Revision ID: 818a9604ada7
Revises: e9741537bc10
Create Date: 2026-06-04 17:18:31.286683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818a9604ada7'
down_revision: Union[str, Sequence[str], None] = 'e9741537bc10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE estadosolicitudservicio ADD VALUE IF NOT EXISTS 'cotizada'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
