"""Add Tenant and Multi-tenant relations

Revision ID: 90775bdddfb4
Revises: 2474690a3266
Create Date: 2026-06-04 15:14:08.628387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90775bdddfb4'
down_revision: Union[str, Sequence[str], None] = '2474690a3266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo_acceso', sa.String(length=50), nullable=True),
    sa.Column('estado_activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_codigo_acceso'), 'tenant', ['codigo_acceso'], unique=True)
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)
    
    # 1. Agregar columna como Nullable temporalmente
    op.add_column('taller', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    # 2. Insertar Tenant Default y actualizar registros existentes
    op.execute("INSERT INTO tenant (nombre, codigo_acceso, estado_activo) VALUES ('Tenant Default', 'DEFAULT', true)")
    op.execute("UPDATE taller SET tenant_id = 1")
    op.execute("UPDATE usuario SET tenant_id = 1")
    
    # 3. Alterar a NOT NULL para la tabla taller
    op.alter_column('taller', 'tenant_id', nullable=False)
    
    op.create_foreign_key(None, 'taller', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usuario', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'tenant_id')
    op.drop_constraint(None, 'taller', type_='foreignkey')
    op.drop_column('taller', 'tenant_id')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_codigo_acceso'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
