"""Add is_active to usuario

Revision ID: c885843b8964
Revises: merge_heads_rev
Create Date: 2026-05-29 10:24:09.008625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c885843b8964'
down_revision: Union[str, Sequence[str], None] = 'merge_heads_rev'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicio_estado'), table_name='servicio')
    op.drop_index(op.f('ix_servicio_fecha'), table_name='servicio')
    op.drop_index(op.f('ix_servicio_taller'), table_name='servicio')
    op.drop_index(op.f('ix_servicio_tecnico_empleado'), table_name='servicio_tecnico')
    op.drop_index(op.f('ix_servicio_tecnico_servicio'), table_name='servicio_tecnico')
    op.drop_index(op.f('ix_servicio_vehiculo_servicio'), table_name='servicio_vehiculo')
    op.drop_index(op.f('ix_servicio_vehiculo_vehiculo'), table_name='servicio_vehiculo')
    op.drop_index(op.f('ix_solicitud_servicio_diagnostico'), table_name='solicitud_servicio')
    op.drop_index(op.f('ix_solicitud_servicio_estado'), table_name='solicitud_servicio')
    op.drop_index(op.f('ix_solicitud_servicio_fecha'), table_name='solicitud_servicio')
    op.drop_index(op.f('ix_solicitud_servicio_taller'), table_name='solicitud_servicio')
    op.drop_constraint(op.f('uq_ubicacion_tecnico_servicio'), 'ubicacion_tecnico', type_='unique')
    op.add_column('usuario', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'is_active')
    op.create_unique_constraint(op.f('uq_ubicacion_tecnico_servicio'), 'ubicacion_tecnico', ['id_servicio', 'id_empleado'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_solicitud_servicio_taller'), 'solicitud_servicio', ['id_taller'], unique=False)
    op.create_index(op.f('ix_solicitud_servicio_fecha'), 'solicitud_servicio', [sa.literal_column('fecha DESC')], unique=False)
    op.create_index(op.f('ix_solicitud_servicio_estado'), 'solicitud_servicio', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitud_servicio_diagnostico'), 'solicitud_servicio', ['id_diagnostico'], unique=False)
    op.create_index(op.f('ix_servicio_vehiculo_vehiculo'), 'servicio_vehiculo', ['id_vehiculo_taller'], unique=False)
    op.create_index(op.f('ix_servicio_vehiculo_servicio'), 'servicio_vehiculo', ['id_servicio'], unique=False)
    op.create_index(op.f('ix_servicio_tecnico_servicio'), 'servicio_tecnico', ['id_servicio'], unique=False)
    op.create_index(op.f('ix_servicio_tecnico_empleado'), 'servicio_tecnico', ['id_empleado'], unique=False)
    op.create_index(op.f('ix_servicio_taller'), 'servicio', ['id_taller'], unique=False)
    op.create_index(op.f('ix_servicio_fecha'), 'servicio', [sa.literal_column('fecha DESC')], unique=False)
    op.create_index(op.f('ix_servicio_estado'), 'servicio', ['estado'], unique=False)
    # ### end Alembic commands ###
