"""add numero to servicio

Revision ID: d755c1e1e82c
Revises: 818a9604ada7
Create Date: 2026-06-10 15:28:16.681204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd755c1e1e82c'
down_revision: Union[str, Sequence[str], None] = '818a9604ada7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicio', sa.Column('numero', sa.Integer(), nullable=True))
    
    # Backfill numero
    op.execute("""
        WITH numbered_services AS (
            SELECT id, row_number() OVER (PARTITION BY id_taller ORDER BY fecha ASC) as rn
            FROM servicio
        )
        UPDATE servicio
        SET numero = numbered_services.rn
        FROM numbered_services
        WHERE servicio.id = numbered_services.id;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicio', 'numero')
    # ### end Alembic commands ###
