"""Add tenant_id to persona

Revision ID: e9741537bc10
Revises: 90775bdddfb4
Create Date: 2026-06-04 15:34:48.603585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9741537bc10'
down_revision: Union[str, Sequence[str], None] = '90775bdddfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'persona', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persona', type_='foreignkey')
    op.drop_column('persona', 'tenant_id')
    # ### end Alembic commands ###
